services:
  postgres:
    image: postgres:16-alpine
    container_name: room-booking-postgres
    environment:
      POSTGRES_DB: room_booking
      POSTGRES_USER: room_booking
      POSTGRES_PASSWORD: room_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U room_booking -d room_booking"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: room-booking-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8080"
    volumes:
      - ./keycloak-realm:/opt/keycloak/data/import

volumes:
  postgres_data:
